name: pulsar_web
description: A simple Dart web framework for building modern web applications.
version: 0.4.3
repository: https://github.com/IgnacioFernandez1311/pulsar_web
homepage: https://pulsar-web.netlify.app

topics:
  - web
  - frontend
  - css

environment:
  sdk: ^3.9.2

dependencies:
  universal_web: ^1.1.1+1
  webdev: ^3.7.2

dev_dependencies:
  build_runner: ^2.10.1
  build_web_compilers: ^4.1.6
  lints: ^6.0.0
